### ISSUE TITLE
Capistrano + crowdin download translations error: Nothing written

### ISSUE THREAD

**Issue by sazzabi** [crowdin/crowdin-cli#122]
Hello, 

I have a capistrano task that downloads translation files using crowdin cli, and sometimes I got this error that fails the deploy:

```
#<Thread:0x000055de0a48f970@/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as adminweb@frontalnginx.internal: cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr exit status: 1 (SSHKit::Runner::ExecuteError)
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stdout: Building ZIP archive with the latest translations for 'fr'/
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stderr: Nothing written
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/command.rb:99:in `exit_status=': cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr exit status: 1 (SSHKit::Command::Failed)
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stdout: Building ZIP archive with the latest translations for 'fr'/
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stderr: Nothing written
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/netssh.rb:169:in `execute_command'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `block in create_command_and_execute'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `tap'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `create_command_and_execute'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:78:in `execute'
	from /srv/lib/capistrano/tasks/crowdin.rake:6:in `block (4 levels) in <top (required)>'
	from /srv/lib/capistrano/tasks/crowdin.rake:5:in `each'
	from /srv/lib/capistrano/tasks/crowdin.rake:5:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:29:in `run'
	from /usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as adminweb@frontalnginx.internal: cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr exit status: 1
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stdout: Building ZIP archive with the latest translations for 'fr'/
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stderr: Nothing written
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
SSHKit::Command::Failed: cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr exit status: 1
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stdout: Building ZIP archive with the latest translations for 'fr'/
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stderr: Nothing written
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/command.rb:99:in `exit_status='
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/netssh.rb:169:in `execute_command'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `block in create_command_and_execute'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `tap'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:145:in `create_command_and_execute'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:78:in `execute'
/srv/lib/capistrano/tasks/crowdin.rake:6:in `block (4 levels) in <top (required)>'
/srv/lib/capistrano/tasks/crowdin.rake:5:in `each'
/srv/lib/capistrano/tasks/crowdin.rake:5:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/backends/abstract.rb:29:in `run'
/usr/local/bundle/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => crowdin:pull
The deploy has failed with an error: Exception while executing as adminweb@frontalnginx.internal: cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr exit status: 1
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stdout: Building ZIP archive with the latest translations for 'fr'/
cd /releases/20191004160920 && crowdin download --config app/config/crowdin/crowdin.yml -l fr stderr: Nothing written
** Invoke deploy:failed (first_time)
** Execute deploy:failed


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [3b9acf5e] 	/

 DEBUG [3b9acf5e] 	

 DEBUG [3b9acf5e] 	-

 DEBUG [3b9acf5e] 	

 DEBUG [3b9acf5e] 	\

 DEBUG [3b9acf5e] 	

 DEBUG [3b9acf5e] 	|

 DEBUG [3b9acf5e] 	/

 DEBUG [3b9acf5e] 	-

 DEBUG [3b9acf5e] 	

 DEBUG [3b9acf5e] 	\

 DEBUG [3b9acf5e] 	

 DEBUG [55f74790] 	Building ZIP archive with the latest translations for 'en'

 DEBUG [55f74790] 	-

 DEBUG [55f74790] 	

 DEBUG [3b9acf5e] 	|

 DEBUG [3b9acf5e] 	

 DEBUG [55f74790] 	\

 DEBUG [55f74790] 	

 DEBUG [3b9acf5e] 	/

make: *** [deploy] Erreur 1

```

It says **Building ZIP archive with the latest translations for 'fr' Nothing written**. When I build project from crowdin management interface, and re-run the deploy job, it succeeds. I don't know what is the problem. 

By the way, I can't manage to have this error on my computer (ubuntu 18.04 / Docker), and the config is okey.

**Comment by andrii-bodnar** [comment]
Hi @sazzabi !
Try to use [CLI 3](https://github.com/crowdin/crowdin-cli-2/tree/cli3#readme). The issue was probably fixed in this version.
